// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: 'us-east-1',
  aws_cognito_identity_pool_id: 'us-east-1:c9b6d8f0-ff33-445c-aec4-c1cf4cab01e3',
  aws_cognito_region: 'us-east-1',
  aws_user_pools_id: 'us-east-1_6iSo5FHun',
  aws_user_pools_web_client_id: '2m2a4itd4s87qbgsth17nbf2fc',
  oauth: {
    domain: 'openandlearn18e45e9e-18e45e9e-dev.auth.us-east-1.amazoncognito.com',
    scope: ['phone', 'email', 'openid', 'profile', 'aws.cognito.signin.user.admin'],
    redirectSignIn: 'exp://192.168.1.28:19000/',
    redirectSignOut: 'exp://192.168.1.28:19000/',
    responseType: 'code'
  },
  federationTarget: 'COGNITO_USER_POOLS'
};

export default awsmobile;
